### ISSUE TITLE
utds引き継ぎに関して

### ISSUE THREAD

**Issue by kokhayas** [tokyodebate/motions#23]
お疲れ様です、2021年utds web担当の林です。お忙しい中すみません、いーふーさんと連絡を取りたいのですがよろしいでしょうか。引き継ぎに関して、writer権限や管理者権限を次期担当者に与えることについて相談したいのですが、連絡いただけると助かります。githubのこちらか,
1234.884.koki@gmail.comのメールまで連絡いただけないでしょうか、よろしくお願いします。m._.m

**Comment by hyper1FU** [comment]
どうもお久しぶりです。林さんにAdmin権限を付与しましたので、次期担当者の権限についてはお任せします。

**Comment by kokhayas** [comment]
連絡をありがとうございます！
utdsのwebを次の人に引き継いでいこうと思います。
今までありがとうございました。

2022年3月9日(水) 20:31 hyper1FU ***@***.***>:

**Comment by kokhayas** [comment]
https://github.com/tokyodebate の他のレポジトリは引き継いだほうが良いのでしょうか? よろしくお願いします。

2022年3月9日(水) 21:36 林洸希 ***@***.***>:

**Comment by kokhayas** [comment]
http://resources.tokyodebate.org/debate-motion/kanto-debate-open/
いーふーさんに質問があるのですがよろしいでしょうか。上の大会を新しく追加したら、wordpressの表示が崩れてしまったのですが、どのように解決すれば良いのか教えていただけないでしょうか。
